apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: finally
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  finally
    app.kubernetes.io/part-of: finally  
  name: finally
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  finally 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  finally
    spec:
      containers:
      - image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-inference
        envFrom:
        - configMapRef:
            name: finally-model-config
        env:
        - name: MODEL_ENDPOINT_BEARER
          valueFrom:
            secretKeyRef:
              name: secret-audio
              key: apikey
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
