apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: finally
  janus-idp.io/tekton: finally
  backstage.io/kubernetes-id: finally
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: finally
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
