apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: finally
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: finally 
  name: finally
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: finally 
